### PR TITLE
add rpc json docs

### PR DESCRIPTION
**Pull request by rawdaGastan**
### Issues

- https://github.com/threefoldtech/zos/issues/2059

### CODE REVIEW

**Comment by muhamadazmy** [comment]
Seems that @timurgordon is working on an OpenRPC specs based on this, openrpc actually defines schema unlike jsonrpc which is just data. So let's see how far he is and contribute on it

**Comment by xmonader** [comment]
@timurgordon where is the issue for openRPC? and where is the active work?

**Comment by timurgordon** [comment]
@xmonader just opened a issue for it https://github.com/freeflowuniverse/crystallib/issues/238. The progress is here: https://github.com/freeflowuniverse/crystallib/tree/development_kristof/zos

**Comment by timurgordon** [comment]
> Seems that @timurgordon is working on an OpenRPC specs based on this, openrpc actually defines schema unlike jsonrpc which is just data. So let's see how far he is and contribute on it

I am not sure if this covers all the primitives we want for ZOS so just did this as a starting point from our chat and from the progress in this issue. We can regenerate the document by changing the client functions to suit the required primitives.

**Comment by muhamadazmy** [comment]
I started a new PR here https://github.com/threefoldtech/zos/pull/2104 to write the specs in open-rpc. I started this as a guide and @rawdaGastan should continue based on that.

I will then make sure to review that it matches what zos can do, and add any missing functionality.

**Pull request closed without merging**
