### PR TITLE
rework auth check

### PR DESCRIPTION
**Pull request by DylanVerstraete**

### CODE REVIEW

**Comment by maxux** [comment]
This maybe work on really old zdb, but new version returns `Authentication disabled` (typo fixed).
Maybe check only on last word `disabled`, to make it generic.

**Comment by DylanVerstraete** [comment]
> This maybe work on really old zdb, but new version returns `Authentication disabled` (typo fixed).
> Maybe check only on last word `disabled`, to make it generic.

Ah, yes indeed

**Comment by DylanVerstraete** [comment]
@maxux can other stuff return errors with `disabled` in it as well? This might cause conflics then

**Review by muhamadazmy — APPROVED** [review]

**Comment by maxux** [comment]
@DylanVerstraete should not. Possible replies are:
- `Authentication disabled`
- `Password too long`
- `OK`
- `Access denied`

**Comment by DylanVerstraete** [comment]
> @DylanVerstraete should not. Possible replies are:
> 
> * `Authentication disabled`
> * `Password too long`
> * `OK`
> * `Access denied`

okay thanks!

**Pull request merged**
