### PR TITLE
zdb: correct the way storage allocation is done for 0-db sub volumes

### PR DESCRIPTION
**Pull request by zaibon**

### CODE REVIEW

**Review by muhamadazmy — COMMENTED** [review]
I don't really see any change here except the code organization

**Comment by zaibon** [comment]
@azertyalex 
the main change is this line: https://github.com/threefoldtech/zos/pull/429/files#diff-9a7c5ba1492d9a09f436c35fc6a52705R67
I now use the size of the selected "volume" instead of the pool.
So before this change we would set the size limit to (pool size + reservations size) which is a number bigger then the disk actually have
And now we do set the limit with (volume current size + reservation size) which is always in the boundaries of the disk size and also correct in term of provisioning.

**Comment by azertyalex** [comment]
> @azertyalex 

I think this was a mistake? @zaibon

**Comment by zaibon** [comment]
@azertyalex indeed my bad. Wrong auto completion. I meant to tag @muhamadazmy

**Pull request merged**
